services:
  analyzer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PIP_TIMEOUT: 600
        PIP_RETRIES: 10
        BUILDKIT_INLINE_CACHE: 1
    container_name: bioanalyzer-dev
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - DEBUG=true
      - WATCHFILES_FORCE_POLLING=true
      - ENVIRONMENT=development
    volumes:
      # Mount source code for live reloading
      - ./app:/app/app
      - ./config:/app/config
      - ./main.py:/app/main.py
      - ./frontend:/app/frontend
      # Data and cache volumes
      - ./data:/app/data
      - ./cache:/app/cache
      - ./results:/app/results
      - ./.env:/app/.env:ro
      # Development volumes
      - ./logs:/app/logs
    networks:
      - bioanalyzer-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Enable auto-restart on file changes
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  nginx:
    build:
      context: .
      dockerfile: deployment/docker/nginx.Dockerfile
    container_name: bioanalyzer-nginx-dev
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - nginx_logs:/var/log/nginx
      - nginx_cache:/var/cache/nginx
      - ./deployment/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # Mount frontend for live reloading
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      analyzer:
        condition: service_healthy
    networks:
      - bioanalyzer-network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: bioanalyzer-redis-dev
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - bioanalyzer-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  nginx_logs:
  nginx_cache:
  redis_data:

networks:
  bioanalyzer-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 